### ISSUE TITLE
verifyPassHash is vulnerable to timing attacks.

### ISSUE THREAD

**Issue by EdOverflow** [HR/CryptoSync#2]
The same applies here:

~~~
exports.verifyPassHash = function (mpkhash, gmpkhash) {
  return _.isEqual(mpkhash, gmpkhash)
}
~~~

https://github.com/HR/CryptoSync/blob/master/src/crypto.js#L194-L196

**Comment by HR** [comment]
@EdOverflow Thanks again for reporting this error here. Not sure about the future of this repo as it hasn't received much interest so it is very behind Crypter. Hence, not working on this. But if you think it is a great idea and would like to contribute then feel free to do so 😄
